events {}

http {
    upstream chat_backend {
        server chat-server-1:5000;
        server chat-server-2:5000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://chat_backend;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
    }
}